okr/urls.py
from django.conf.urls import url

from okr import views


urlpatterns = [
    url(r'^$', views.visible, name='index'),
    url(r'^archived/$', views.archived, name='archived'),
    url(r'^archived/page/(?P<page>\d+)$', views.archived_paged, name='archived_paged'),
    url(r'^edit_kr/$', views.edit_kr, name='edit_kr'),
    url(r'^show_kr/(?P<id>\d+)$', views.show_kr, name='show_kr'),
    url(r'^add_kr/(?P<o>\d+)$', views.add_kr, name='add_kr'),
    url(r'^delete_kr/(?P<id>\d+)/$', views.delete_kr, name='delete_kr'),
    url(r'^add_obj/$', views.add_obj, name='add_obj'),
    url(r'^edit_obj/(?P<id>\d+)$', views.edit_obj, name='edit_obj'),
    url(r'^delete_obj/(?P<id>\d+)/$', views.delete_obj, name='delete_obj'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

okr_project/urls.py
from django.conf.urls import include, url
from django.contrib.auth.models import User, Group
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

# remove "Auth" menu's from admin
admin.site.unregister(Group)


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^okr/', include('okr.urls', namespace='okr')),
]


# Static content
urlpatterns += staticfiles_urlpatterns()

okr/models.py
# -*- coding: utf-8 -*-
from django.db.models import Sum
from django.db import models
from django.contrib.auth.models import User


class Objective(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=200)
	pub_date = models.DateField('publication date', auto_now_add=True)
	end_date = models.DateField('end date')

	def __unicode__(self):
		return self.name

	def percentage_total(self):
		num_kr = self.keyresult_set.count()
		if num_kr > 0:
			sum_percentages = self.keyresult_set.aggregate(percentage_total=Sum("percentage"))
			return sum_percentages['percentage_total'] / num_kr
		else:
			return 0.0


class KeyResult(models.Model):
	POSITIVE = '0'
	NEGATIVE = '1'
	BINARY = '2'
	TYPE_DATA_CHOICES = (
		('0', 'Positive'),
		('1', 'Negative'),
		('2', 'Binary')
	)

	objective = models.ForeignKey(Objective)
	name = models.CharField(max_length=200)
	type_data = models.CharField('Type',
								 max_length=1,
								 choices=TYPE_DATA_CHOICES,
								 default=POSITIVE)
	obtained = models.FloatField(default=0)
	expected = models.FloatField()
	percentage = models.FloatField()
	pub_date = models.DateField('publication date', auto_now_add=True)

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.percentage = calculate_percentage(self.type_data, self.obtained, self.expected)
		super(KeyResult, self).save(*args, **kwargs)


def calculate_percentage(type_data, obtained, expected):
	# Round without decimals
	if type_data == KeyResult.POSITIVE:
		return 100 * obtained / expected
	elif type_data == KeyResult.NEGATIVE:
		return 100 * (1 - obtained / expected)
	elif type_data == KeyResult.BINARY:
		if obtained == 0:
			return 0
		else:
			return 100

okr/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from okr.models import Objective, KeyResult
import datetime


class ObjectiveForm(ModelForm):

	class Meta:
		model = Objective
		fields = ('name', 'end_date')

	# Configured to Bootstrap classes
	def __init__(self, *args, **kwargs):
		super(ObjectiveForm, self).__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control input-sm'

	def clean(self):
		end_date = self.cleaned_data.get('end_date', None)

		# end_date >= pub_date
		if end_date and (end_date < datetime.date.today()):
			self._errors['end_date'] = 'End date must be later than today.'

		return self.cleaned_data



class KeyResultForm(ModelForm):

	class Meta:
		model = KeyResult
		fields = ('name', 'type_data', 'expected', 'obtained')

	# Configured to Bootstrap classes
	def __init__(self, *args, **kwargs):
		super(KeyResultForm, self).__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control input-sm'

	def clean(self):
		obtained = self.cleaned_data.get('obtained', None)
		expected = self.cleaned_data.get('expected', None)
		type_data = self.cleaned_data.get('type_data', None)

		# obtained <= expected
		if ( obtained > expected ):
			self._errors['obtained'] = 'Obtained can not be greater than expected.'
			# raise ValidationError('Obtained can not be greater than expected.')

		# if it's binary: obtained = 0 or 1 and expected = 1
		if ( type_data == KeyResult.BINARY ):
			if not (obtained == 0 or obtained == 1):
				self._errors['obtained'] = 'Obtained must be 0 or 1.'
				# raise ValidationError('Obtained must be 0 or 1.')

			if not (expected == 1):
				self._errors['expected'] = 'Expected must be 1.'
				# raise ValidationError('Expected must be 1.')

		return self.cleaned_data


class AuthForm(AuthenticationForm):

	# Configured to Bootstrap classes
	def __init__(self, *args, **kwargs):
		super(AuthForm, self).__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control input-sm'

	def clean(self):
		username = self.cleaned_data.get('username', None)
		password = self.cleaned_data.get('password', None)
		user = authenticate(username=username, password=password)
		if not user:
			raise ValidationError("Sorry, that login was invalid. Please try again.")
		else:
			if not user.is_active:
				raise ValidationError("Sorry, that user is inactive.")

		return self.cleaned_data

	def login(self, request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		return user


class RegisterForm(UserCreationForm):
	email = forms.EmailField(required=True)

	# Configured to Bootstrap classes
	def __init__(self, *args, **kwargs):
		super(RegisterForm, self).__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control input-sm'

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user


class ChangePasswordForm(PasswordChangeForm):

	# Configured to Bootstrap classes
	def __init__(self, user, *args, **kwargs):
		super(ChangePasswordForm, self).__init__(user, *args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control input-sm'

okr/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, Http404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from okr.forms import ObjectiveForm, KeyResultForm, AuthForm, RegisterForm, ChangePasswordForm
from okr.models import Objective, KeyResult


#############################################################################
# Key Results
#############################################################################

# Auxiliar functions
def get_details(type_data, obtained, expected):
    if type_data == KeyResult.POSITIVE:
        details = 'Obtained %d of %d' % (obtained, expected)
    elif type_data == KeyResult.NEGATIVE:
        details = 'Failed %d of %d' % (obtained, expected)
    elif type_data == KeyResult.BINARY:
        if obtained == 0:
            details = 'No achieved'
        else:
            details = 'Achieved'
    return details


def list_okrs(objectives_list, show_forms=False):
    okr_list = []
    for o in objectives_list:
        key_results_list = KeyResult.objects.filter(objective=o).order_by('-pub_date')

        keyresults = []
        if key_results_list:
            for k in key_results_list:
                keyresults.append({
                    'id': k.id,
                    'name': k.name,
                    'percentage': int(k.percentage),
                    'details': get_details(k.type_data, k.obtained, k.expected),
                })
                if show_forms:
                    keyresults[-1]['form'] = KeyResultForm(instance=k)

        okr_list.append({
            'objective': o,
            'percentage': int(o.percentage_total()),
            'keyresults': keyresults,
        })

    return okr_list


@login_required
def visible(request):
    objectives_list = Objective.objects.filter(
        user=request.user,
        end_date__gte=timezone.now()).order_by('end_date')
    context = {'okr_list': list_okrs(objectives_list, True)}
    return render(request, 'okr/visible.html', context)


@login_required
def archived(request):
    return archived_paged(request, 1)


@login_required
def archived_paged(request, page):
    objectives_list = Objective.objects.filter(user=request.user, end_date__lt=timezone.now()).order_by('end_date')

    okr_list = list_okrs(objectives_list)
    paginator = Paginator(okr_list, 7)

    try:
        okrs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        okrs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        okrs = paginator.page(paginator.num_pages)

    return render(request, 'okr/archived.html', {'okr_list': okrs})


@login_required
def edit_kr(request):
    if not request.is_ajax(): raise Http404

    if request.method == 'POST' and request.POST.has_key('id'):
        kr = get_object_or_404(KeyResult, id=request.POST['id'], objective__user=request.user)
        form = KeyResultForm(request.POST, instance=kr)
        if form.is_valid():
            form.save()
            response = {
                'status': 'ok',
                'data': {
                    'name': kr.name,
                    'percentage': int(kr.percentage),
                    'details': get_details(kr.type_data, kr.obtained, kr.expected),
                    'percentage_total': int(kr.objective.percentage_total()),
                }
            }
        else:
            response = {
                'status': 'error',
                'data': form.errors
            }
    else:
        response = {'status': 'method-error'}
    return JsonResponse(response)


@login_required
def show_kr(request, id):
    if not request.is_ajax(): raise Http404
    kr = get_object_or_404(KeyResult, id=id, objective__user=request.user)
    response = {
        'name': kr.name,
        'type_data': kr.type_data,
        'expected': kr.expected,
        'obtained': kr.obtained
    }
    return JsonResponse(response)


@login_required
def add_kr(request, o):
    obj = get_object_or_404(Objective, id=o, user=request.user)
    form = KeyResultForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        kr = form.save(commit=False)
        kr.objective = obj
        kr.save()
        return redirect('okr:index')
    context = {
        'form': form,
        'objective': obj
    }
    return render(request, "okr/add_kr.html", context)


@login_required
def delete_kr(request, id):
    get_object_or_404(KeyResult, pk=id, objective__user=request.user).delete()
    return redirect('okr:index')


#############################################################################
# Objectives
#############################################################################

@login_required
def add_obj(request):
    form = ObjectiveForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        o = form.save(commit=False)
        o.user = request.user
        o.save()
        return redirect('okr:index')
    return render(request, "okr/add_obj.html", {'form': form})


@login_required
def edit_obj(request, id):
    obj = get_object_or_404(Objective, id=id, user=request.user)
    if request.method == "POST":
        form = ObjectiveForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('okr:index')
    else:
        form = ObjectiveForm(instance=obj)
    context = {
        'form': form,
        'objective': obj
    }
    return render(request, "okr/edit_obj.html", context)


@login_required
def delete_obj(request, id):
    get_object_or_404(Objective, pk=id, user=request.user).delete()
    return redirect('okr:index')


#############################################################################
# Users
#############################################################################

def user_login(request):
    if request.user.is_authenticated():
        return redirect('okr:index')

    form = AuthForm(request, request.POST or None)
    if request.method == "POST" and form.is_valid:
        user = form.login(request)
        if user:
            # Username and password are correct and user is marked as "active"
            login(request, user)
            return redirect('okr:index')
    return render(request, 'okr/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('okr:login')


def register(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        # Login
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('okr:index')
    return render(request, 'okr/register.html', {'form': form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('okr:index')
    else:
        form = ChangePasswordForm(user=request.user)
    return render(request, 'okr/change_password.html', {'form': form})

okr/templates/okr/add_kr.html
{% extends "okr/base_logged.html" %}

{% block title %}Add Key Result{% endblock %}

{% block nav_visible %} class="active"{% endblock %}

{% block content %}
	<article class="okr jumbotron">
		<h2>{{ objective.name }} </h2>
		<h4>Add new key result</h4>
		<form method="post" action="{% url 'okr:add_kr' objective.id %}" class="form-horizontal">
			{% csrf_token %}
			{% if form.non_field_errors %}
          	<div class="alert alert-danger">
            	{{ form.non_field_errors|striptags }}
          	</div>
      		{% endif %}
			{% for field in form.visible_fields %}
			{% if not field.errors %}
			<div class="form-group">
			{% else %}
			<div class="form-group has-error">
			{% endif %}
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
					{{ field.label }}:
				</label>
				<div class="col-sm-9">
					<div class="error-msg" style="display:block">
					{{ field.errors|striptags }}
					</div>
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<label for="id_achieved" class="col-sm-2 control-label">
					Achieved:
				</label>
				<div class="col-sm-9">
					<label class="radio-inline">
						<input type="radio" name="achieved" id="id_achieved-yes" value="1"> Yes
					</label>
					<label class="radio-inline">
						<input type="radio" name="achieved" id="id_achieved-no" value="0"> No
					</label>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-9">
				  	<input id="add-kr" type="submit" class="btn btn-primary btn-sm" value="Add">
				  	<input id="cancel" type="button" class="btn btn-default btn-sm" value="Cancel">
				</div>
			</div>
		</form>
	</article>
{% endblock %}

okr/templates/okr/add_obj.html
{% extends "okr/details_obj.html" %}

{% block title %}Add Objective{% endblock %}

{% block nav_visible %} class="active"{% endblock %}

{% block title_info %}
<h4>Add new objective</h4>
{% endblock %}

{% block form_action %}{% url 'okr:add_obj' %}{% endblock %}

{% block submit_button %}
<input id="add-obj" type="submit" class="btn btn-primary btn-sm" value="Add">
{% endblock %}

okr/templates/okr/archived.html
{% extends "okr/list.html" %}

{% block title %}Archived OKR's{% endblock %}

{% block nav_archived %} class="active"{% endblock %}

{% block okr-name %}
	{{ okr.objective.name }}
{% endblock %}

{% block paginator %}
<!--<ul class="pagination">
	<li class="disabled"><a href="#">&laquo;</a></li>
	<li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
	<li><a href="#">2</a></li>
	<li><a href="#">3</a></li>
	<li class="disabled"><a href="#">...</a></li>
	<li><a href="#">9</a></li>
	<li><a href="#">10</a></li>
	<li><a href="#">11</a></li>
	<li><a href="#">&raquo;</a></li>
</ul>-->
<ul class="pagination">
	{% if okr_list.has_previous %}
		<li><a href="{% url 'okr:archived_paged' okr_list.previous_page_number %}">&laquo;</a></li>
	{% else %}
		<li class="disabled"><a href="#">&laquo;</a></li>
	{% endif %}
	{% for page in okr_list.paginator.page_range %}
		{% if page == okr_list.number %}
			<li class="active"><a href="{% url 'okr:archived_paged' page %}">{{ page }} <span class="sr-only">(current)</span></a></li>
		{% else %}
			<li><a href="{% url 'okr:archived_paged' page %}">{{ page }}</a></li>
		{% endif %}
	{% endfor %}
	{% if okr_list.has_next %}
		<li><a href="{% url 'okr:archived_paged' okr_list.next_page_number %}">&raquo;</a></li>
	{% else %}
		<li class="disabled"><a href="#">&raquo;</a></li>
	{% endif %}
</ul>
{% endblock %}

okr/templates/okr/base_logged.html
{% extends "okr/base.html" %}

{% block nav %}
<nav class="nav nav-pills pull-right">
	<li{% block nav_visible %}{% endblock %}>
		<a href="{% url 'okr:index' %}">Your OKRs</a>
	</li>
	<li{% block nav_archived %}{% endblock %}>
		<a href="{% url 'okr:archived' %}">Archived</a>
	</li>
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<span class="glyphicon glyphicon-cog"></span>
		</a>
		<ul class="dropdown-menu">
				<li>
					<a href="{% url 'okr:change_password' %}">Change password</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="{% url 'okr:logout' %}">Log out</a>
				</li>
		</ul>
	</li>
</nav>
{% endblock %}

okr/templates/okr/change_password.html
{% extends "okr/base_logged.html" %}

{% block title %}Change password{% endblock %}

{% block content %}
	<article class="okr jumbotron">
		<h2>Change password:</h2>
		<form method="post" action="{% url 'okr:change_password' %}" class="form-horizontal">
			{% csrf_token %}
			{% if form.non_field_errors %}
          	<div class="alert alert-danger">
            	{{ form.non_field_errors|striptags }}
          	</div>
      		{% endif %}
			{% for field in form.visible_fields %}
			{% if not field.errors %}
			<div class="form-group">
			{% else %}
			<div class="form-group has-error">
			{% endif %}
				<label for="{{ field.id_for_label }}" class="col-sm-3 control-label">
					{{ field.label }}:
				</label>
				<div class="col-sm-9">
					<div class="error-msg" style="display:block">
					{{ field.errors|striptags }}
					</div>
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-3 col-sm-9">
				  	<input id="change_password" type="submit" class="btn btn-primary btn-sm" value="Change password">
				  	<input id="cancel" type="button" class="btn btn-default btn-sm" value="Cancel">
				</div>
			</div>
		</form>
	</article>
{% endblock %}

okr/templates/okr/edit_obj.html
{% extends "okr/details_obj.html" %}

{% block title %}Edit Objective{% endblock %}

{% block nav_visible %} class="active"{% endblock %}


{% block title_info %}
<h2>{{ objective.name }}</h2>
<h4>Edit objective</h4>
{% endblock %}

{% block form_action %}{% url 'okr:edit_obj' objective.id %}{% endblock %}

{% block submit_button %}
<input id="edit-obj" type="submit" class="btn btn-primary btn-sm" value="Edit">
{% endblock %}

{% block delete_link %}
<small class="pull-right"><a href="{% url 'okr:delete_obj' objective.id %}" class="delete">Delete</a></small>
{% endblock %}

okr/templates/okr/error.html
{% extends "okr/base.html" %}

{% block title %}Oops{% endblock %}

{% block content %}
	<h2>Oops! something went wrong.</h2>
	<a href="{% url 'okr:index' %}">Go back!</a>
{% endblock %}

okr/templates/okr/index.html
{% extends "okr/list.html" %}

{% block title %}OKR Management System{% endblock %}

{% block nav %}
	<li class="active">
		<a href="{% url 'okr:index' %}">Your OKRs</a>
	</li>
	<li>
		<a href="{% url 'okr:archived' %}">Archived</a>
	</li>
{% endblock %}

{% block add_obj %}
	<small class="pull-left" id="add-obj">
		<a href="{% url 'okr:add_obj' %}">
			<span class="glyphicon glyphicon-plus"></span>
			Add Objective
		</a>
	</small>
{% endblock %}

{% block okr-name %}
	<a href="{% url 'okr:edit_obj' okr.objective.id %}">{{ okr.objective.name }}</a>
{% endblock %}

{% block edit-button %}
	<button type="button" class="btn btn-primary btn-xs" id="kredit-{{ keyresult.id }}">
		<span class="glyphicon glyphicon-pencil"></span>
	</button>
{% endblock %}

{% block edit-menu %}
	<div class="edit" id="edit-{{ keyresult.id }}">
		<form method="post" class="form-horizontal">
			{% csrf_token %}
			{% for field in keyresult.form.visible_fields %}
				<div class="form-group">
					<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
						{{ field.label }}:
					</label>
					<div class="col-sm-9">
						<div id="krerror-{{ keyresult.id }}-{{ field.id_for_label }}" class="error-msg">
						{# {{ field.errors }} #}
						</div>
						{# {{ field.help_text}} #}
						{{ field }}
					</div>
				</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-9">
				  	<input id="krbtn-{{ keyresult.id }}" type="button" class="btn btn-primary btn-sm" value="Save">
				  	<input id="krcancel-{{ keyresult.id }}" type="button" class="btn btn-default btn-sm" value="Cancel">
				</div>
			</div>
		</form>
		<small class="pull-right"><a href="{% url 'okr:delete_kr' keyresult.id %}" class="delete">Delete</a></small>
		<div style='clear:both'></div>
	</div>
{% endblock %}

{% block add-kr %}
	<small class="pull-left">
		<a href="{% url 'okr:add_kr' okr.objective.id %}">
			<span class="glyphicon glyphicon-plus"></span>
			Add Key Result
		</a>
	</small>
{% endblock %}

okr/templates/okr/login.html
{% extends "okr/base.html" %}

{% block title %}OKR Management System{% endblock %}

{% block content %}
	<article class="login">
		<h2>Welcome:</h2>
		<form method="post" action="{% url 'okr:login' %}" class="form-horizontal">
			{% csrf_token %}
			{% if form.non_field_errors %}
          	<div class="alert alert-danger">
            	{{ form.non_field_errors|striptags }}
          	</div>
      		{% endif %}
			{% for field in form %}
			{% if not field.errors %}
			<div class="form-group">
			{% else %}
			<div class="form-group has-error">
			{% endif %}
				<label for="{{ field.id_for_label }}" class="col-sm-3 control-label">
					{{ field.label }}:
				</label>
				<div class="col-sm-9">
					<div class="error-msg" style="display:block">
					{{ field.errors|striptags }}
					</div>
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-3 col-sm-9">
				  	<input id="login" type="submit" class="btn btn-primary btn-sm" value="Login">
				</div>
			</div>
		</form>
		<div id="login-register-info">
			Don't have an account?
			<a href="{% url 'okr:register' %}">Register now</a>
		</div>
	</article>
{% endblock %}

okr/templates/okr/register.html
{% extends "okr/base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
	<article class="okr jumbotron">
		<h2>Enter your information:</h2>
		<form method="post" action="{% url 'okr:register' %}" class="form-horizontal">
			{% csrf_token %}
			{% if form.non_field_errors %}
          	<div class="alert alert-danger">
            	{{ form.non_field_errors|striptags }}
          	</div>
      		{% endif %}
			{% for field in form.visible_fields %}
			{% if not field.errors %}
			<div class="form-group">
			{% else %}
			<div class="form-group has-error">
			{% endif %}
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
					{{ field.label }}:
				</label>
				<div class="col-sm-9">
					<div class="error-msg" style="display:block">
					{{ field.errors|striptags }}
					</div>
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-9">
				  	<input id="register" type="submit" class="btn btn-primary btn-sm" value="Register">
				</div>
			</div>
		</form>
		<div id="login-register-info">
			Already a member?
			<a href="{% url 'okr:login' %}">Login</a>
		</div>
	</article>
{% endblock %}

okr/templates/okr/visible.html
{% extends "okr/list.html" %}

{% block title %}OKR Management System{% endblock %}

{% block nav_visible %} class="active"{% endblock %}

{% block add_obj %}
	<small class="pull-left" id="new-obj">
		<a href="{% url 'okr:add_obj' %}">
			<span class="glyphicon glyphicon-plus"></span>
			Add Objective
		</a>
	</small>
{% endblock %}

{% block okr-name %}
	<a href="{% url 'okr:edit_obj' okr.objective.id %}">{{ okr.objective.name }}</a>
{% endblock %}

{% block edit-button %}
	<button type="button" class="btn btn-primary btn-xs" id="kredit-{{ keyresult.id }}">
		<span class="glyphicon glyphicon-pencil"></span>
	</button>
{% endblock %}

{% block edit-menu %}
	<div class="edit" id="edit-{{ keyresult.id }}">
		<form method="post" class="form-horizontal">
			{% csrf_token %}
			{% for field in keyresult.form.visible_fields %}
			<div class="form-group">
				<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
					{{ field.label }}:
				</label>
				<div class="col-sm-9">
					<div id="krerror-{{ keyresult.id }}-{{ field.id_for_label }}" class="error-msg">
					{# {{ field.errors }} #}
					</div>
					{# {{ field.help_text}} #}
					{{ field }}
				</div>
			</div>
			{% endfor %}
			<div class="form-group">
				<label for="id_achieved" class="col-sm-2 control-label">
					Achieved:
				</label>
				<div class="col-sm-9">
					<label class="radio-inline">
						<input type="radio" name="achieved" id="id_achieved-yes" value="1"> Yes
					</label>
					<label class="radio-inline">
						<input type="radio" name="achieved" id="id_achieved-no" value="0"> No
					</label>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-9">
					<input id="krbtn-{{ keyresult.id }}" type="button" class="btn btn-primary btn-sm" value="Save">
					<input id="krcancel-{{ keyresult.id }}" type="button" class="btn btn-default btn-sm" value="Cancel">
				</div>
			</div>
		</form>
		<small class="pull-right"><a href="{% url 'okr:delete_kr' keyresult.id %}" class="delete">Delete</a></small>
		<div style='clear:both'></div>
	</div>
{% endblock %}

{% block add-kr %}
	<small class="pull-left">
		<a href="{% url 'okr:add_kr' okr.objective.id %}">
			<span class="glyphicon glyphicon-plus"></span>
			Add Key Result
		</a>
	</small>
{% endblock %}